name: Build Comment 9 Acron Image

on:
  push:
    branches:
    - main
    paths:
    - comment9/**

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: acorn-io/actions-setup@v1
      - uses: acorn-io/actions-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker meta from GitHub events
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/sysu-ecnc/comment9
          tags: |
            type=sha
      - name: Build and Push
        run: |
          cd comment9
          acorn build -t ${{ steps.meta.outputs.tags }}
          acorn push ${{ steps.meta.outputs.tags }}